stages:
  train:
    cmd: python src/train.py
    deps:
    - data/train
    - src/train.py
    - src/utils.py
    - params.yaml
    outs:
    - models/model.pt
    - reports/train_params.yaml:
        cache: false
    metrics:
    - reports/train_metrics.csv:
        cache: false
  test:
    cmd: python src/predict.py
    deps:
      - data/test
      - models/model.pt
      - src/predict.py